// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY2ORjVe2GP9C_RGGz8VupDmWQUl8Djdc',
    appId: '1:454292584119:web:6fca3211cbb264b4b1ff32',
    messagingSenderId: '454292584119',
    projectId: 'huishoudelijkdelen',
    authDomain: 'huishoudelijkdelen.firebaseapp.com',
    storageBucket: 'huishoudelijkdelen.firebasestorage.app',
    measurementId: 'G-6Q9MPBL9P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJwfvn4RsNo_I7WGq7V2Y4X7jOGScUCSY',
    appId: '1:454292584119:android:65cfd574394b7f4eb1ff32',
    messagingSenderId: '454292584119',
    projectId: 'huishoudelijkdelen',
    storageBucket: 'huishoudelijkdelen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0VYdikr3MJw61l4geHMxzNFRCbVVrjg',
    appId: '1:454292584119:ios:36ea49466571b4a6b1ff32',
    messagingSenderId: '454292584119',
    projectId: 'huishoudelijkdelen',
    storageBucket: 'huishoudelijkdelen.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs0VYdikr3MJw61l4geHMxzNFRCbVVrjg',
    appId: '1:454292584119:ios:36ea49466571b4a6b1ff32',
    messagingSenderId: '454292584119',
    projectId: 'huishoudelijkdelen',
    storageBucket: 'huishoudelijkdelen.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY2ORjVe2GP9C_RGGz8VupDmWQUl8Djdc',
    appId: '1:454292584119:web:b3df6eec8537a982b1ff32',
    messagingSenderId: '454292584119',
    projectId: 'huishoudelijkdelen',
    authDomain: 'huishoudelijkdelen.firebaseapp.com',
    storageBucket: 'huishoudelijkdelen.firebasestorage.app',
    measurementId: 'G-LBWF33LCH1',
  );
}
